export enum NodeType {
  ROOT = 'ROOT',

  COMMENT = 'COMMENT',
  NL = 'NL',
  WHITESPACE = 'WHITESPACE',
  JOINING = 'JOINING',

  INTEGER = 'INTEGER',
  FLOAT = 'FLOAT',
  CHAR = 'CHAR',
  STRING = 'STRING',

  ID = 'ID',
  OBJECT = 'OBJECT',
  ARRAY = 'ARRAY',
  GROUP = 'GROUP',

  OPEN = 'OPEN',
  CLOSE = 'CLOSE',
  COMMA = 'COMMA',

  OPERATOR = 'OPERATOR',
  KEYWORD = 'KEYWORD',
  MODIFIER = 'MODIFIER',

  INFIX = 'INFIX',
  INVOKE = 'INVOKE',
  POSTFIX = 'POSTFIX',
  PREFIX = 'PREFIX',

  PARAMETERS = 'PARAMETERS',
  PARAMETER = 'PARAMETER',
  ARGUMENTS = 'ARGUMENTS',
  ARGUMENT = 'ARGUMENT',

  UNKNOWN = 'UNKNOWN',
}
