export enum NodeType {
  ROOT = 'ROOT',

  HIDDEN = 'HIDDEN',
  COMMENT = 'COMMENT',
  NL = 'NL',
  WHITESPACE = 'WHITESPACE',
  JOINING = 'JOINING',

  UNKNOWN = 'UNKNOWN',

  ID = 'ID',
  INTEGER = 'INTEGER',
  CHAR = 'CHAR',
  STRING = 'STRING',
  OBJECT = 'OBJECT',
  ARRAY = 'ARRAY',
  GROUP = 'GROUP',
  OPEN = 'OPEN',
  CLOSE = 'CLOSE',
  OPERATOR = 'OPERATOR',
  KEYWORD = 'KEYWORD',
  COMMA = 'COMMA',

  INFIX = 'INFIX',
  INVOKE = 'INVOKE',
  POSTFIX = 'POSTFIX',
  PREFIX = 'PREFIX',
  FLOAT = 'FLOAT',

  MODIFIER = 'MODIFIER',
  PARAMETERS = 'PARAMETERS',
  PARAMETER = 'PARAMETER',
  ARGUMENTS = 'ARGUMENTS',
  ARGUMENT = 'ARGUMENT',
}
