import { String2 } from '~/lib/core';

export enum NodeType {
  LEXICAL = 'LEXICAL',
  ID = 'ID-LEXICAL',
  NL = 'NL-LEXICAL',
  STRING = 'STRING-LEXICAL',
  INTEGER = 'INTEGER-LEXICAL',
  OPERATOR = 'OPERATOR-LEXICAL',
  UNKNOWN = 'UNKNOWN-LEXICAL',
  WHITESPACE = 'WHITESPACE-LEXICAL',
  JOINING = 'JOINING-LEXICAL',
  OPEN = 'OPEN-LEXICAL',
  CLOSE = 'CLOSE-LEXICAL',
  COMMA = 'COMMA-LEXICAL',

  SYNTAX = 'SYNTAX',
  ARRAY = 'ARRAY-SYNTAX',
  BODY = 'BODY-SYNTAX',
  LADDER = 'LADDER-SYNTAX',
  INFIX = 'INFIX-SYNTAX',
  INVOKE = 'INVOKE-SYNTAX',
  POSTFIX = 'POSTFIX-SYNTAX',
  PREFIX = 'PREFIX-SYNTAX',
  FLOAT = 'FLOAT-SYNTAX',
  MEMBER = 'MEMBER-SYNTAX',

  SEMANTIC = 'SEMANTIC',
  DECLARATION = 'DECLARATION-SEMANTIC',
}

export interface Node {
  type: NodeType | String2;
}
