import { Integer } from '~/lib/core';

export type SyntaxNode = Node;

export interface Token extends Node {
  start: Integer;
  stop: Integer;
}

export interface Node {
  $: NodeType;
}

export enum NodeType {
  HIDDEN = 'HIDDEN',
  COMMENT = 'COMMENT',
  NL = `NL ${HIDDEN}`,
  WHITESPACE = `WHITESPACE ${HIDDEN}`,
  COMMENT_LINE = `COMMENT_LINE ${HIDDEN} ${COMMENT}`,
  COMMENT_BLOCK = `COMMENT_BLOCK ${HIDDEN} ${COMMENT}`,

  ID = 'ID',
  STRING = 'STRING',
  GROUP = 'GROUP',
  INTEGER = 'INTEGER',
  OPERATOR = 'OPERATOR',
  MODIFIER = 'MODIFIER',
  KEYWORD = 'KEYWORD',
  UNKNOWN = 'UNKNOWN',
  JOINING = 'JOINING',
  OPEN = 'OPEN',
  CLOSE = 'CLOSE',
  COMMA = 'COMMA',
  STATEMENT = 'STATEMENT',

  ARRAY = 'ARRAY',
  BODY = 'BODY',
  INFIX = 'INFIX',
  INVOKE = 'INVOKE',
  POSTFIX = 'POSTFIX',
  PREFIX = 'PREFIX',
  FLOAT = 'FLOAT',
  MEMBER = 'MEMBER',
  DECLARATION = 'DECLARATION',
  // ID_DECLARATION = 'ID_DECLARATION',
  // FUNCTION_DECLARATION = 'FUNCTION_DECLARATION',
  // LAMBDA_DECLARATION = 'LAMBDA_DECLARATION',

  // DECLARATION = 'DECLARATION',
  // FUNCTION_VALUE_DECLARATION = 'FUNCTION_VALUE_DECLARATION',
  // FUNCTION_BODY_DECLARATION = 'FUNCTION_BODY_DECLARATION',
  // LAMBDA_VALUE_DECLARATION = 'LAMBDA_VALUE_DECLARATION',
  // LAMBDA_BODY_DECLARATION = 'LAMBDA_BODY_DECLARATION',
  TYPE = 'TYPE',
  VALUE = 'VALUE',
}
