import { Integer, String2 } from '~/lib/core';

export enum NodeType {
  ID = 'ID',
  NL = 'NL',
  STRING = 'STRING',
  GROUP = 'GROUP',
  INTEGER = 'INTEGER',
  OPERATOR = 'OPERATOR',
  MODIFIER = 'MODIFIER',
  KEYWORD = 'KEYWORD',
  UNKNOWN = 'UNKNOWN',
  WHITESPACE = 'WHITESPACE',
  JOINING = 'JOINING',
  OPEN = 'OPEN',
  CLOSE = 'CLOSE',
  COMMA = 'COMMA',
  STATEMENT = 'STATEMENT',

  ARRAY = 'ARRAY',
  BODY = 'BODY',
  INFIX = 'INFIX',
  INVOKE = 'INVOKE',
  POSTFIX = 'POSTFIX',
  PREFIX = 'PREFIX',
  FLOAT = 'FLOAT',
  MEMBER = 'MEMBER',
  DECLARATION = 'DECLARATION',
  // ID_DECLARATION = 'ID_DECLARATION',
  // FUNCTION_DECLARATION = 'FUNCTION_DECLARATION',
  // LAMBDA_DECLARATION = 'LAMBDA_DECLARATION',

  // DECLARATION = 'DECLARATION',
  // FUNCTION_VALUE_DECLARATION = 'FUNCTION_VALUE_DECLARATION',
  // FUNCTION_BODY_DECLARATION = 'FUNCTION_BODY_DECLARATION',
  // LAMBDA_VALUE_DECLARATION = 'LAMBDA_VALUE_DECLARATION',
  // LAMBDA_BODY_DECLARATION = 'LAMBDA_BODY_DECLARATION',
  TYPE = 'TYPE',
  VALUE = 'VALUE',
}

export interface Node {
  $: NodeType | String2;
  start: Integer;
  stop: Integer;
}
