import { createSimpleTreeType } from './tree/type/type-helper';
import { TypeTree } from './tree/type/type.tree';

export const BaseTypes = {
    Undefined: createSimpleTreeType('Undefined'),
    Null: createSimpleTreeType('Null'),
    Any: createSimpleTreeType('Any'),
    Boolean: createSimpleTreeType('Boolean'),
    Integer: createSimpleTreeType('Integer'),
    Float: createSimpleTreeType('Float'),
    String: createSimpleTreeType('String'),
};

export function getOperationType(operator: string, left: TypeTree, right: TypeTree) {
    if (!left || !right) return BaseTypes.Undefined;
    // return variations_cross[`${left.asSimple?.name} ${operator} ${right.asSimple?.name}`];
    return generated_variations[`${left.asSimple?.name} ${operator} ${right.asSimple?.name}`];
}

// let variations = {
//     'Undefined +-^*/ Undefined, Null, Any, Boolean, Integer, Float, String': BaseTypes.Undefined,
//     'Null +-^*/ Null, Any, Boolean, Integer, Float, String': BaseTypes.Undefined,
//     'Any +-^*/ Any, Boolean, Integer, Float, String': BaseTypes.Any,
//     'Boolean +-^*/ Boolean, Integer': BaseTypes.Integer,
//     'Boolean +-^*/ Float': BaseTypes.Float,
//     'Boolean +-^*/ String': BaseTypes.Undefined,
//     'Integer +-^*/ Integer': BaseTypes.Integer,
//     'Integer +-^*/ Float': BaseTypes.Float,
//     'Integer +-^*/ String': BaseTypes.String,
//     'String +-^*/ String': BaseTypes.String,
// };

// const variations_cross = {};

// for (const [key, val] of Object.entries(variations)) {
//     const splitted = key.split(' ');
//     const left = splitted[0];
//     const operations = splitted[1].split('');
//     const rights = splitted.slice(2).map((x) => x.replace(',', ''));

//     for (const op of operations) {
//         for (const right of rights) {
//             variations_cross[`${left} ${op} ${right}`] = val;
//             variations_cross[`${right} ${op} ${left}`] = val;
//         }
//     }
// }

const generated_variations = {
    'Undefined + Undefined': BaseTypes.Undefined,
    'Undefined + Null': BaseTypes.Undefined,
    'Null + Undefined': BaseTypes.Undefined,
    'Undefined + Any': BaseTypes.Undefined,
    'Any + Undefined': BaseTypes.Undefined,
    'Undefined + Boolean': BaseTypes.Undefined,
    'Boolean + Undefined': BaseTypes.Undefined,
    'Undefined + Integer': BaseTypes.Undefined,
    'Integer + Undefined': BaseTypes.Undefined,
    'Undefined + Float': BaseTypes.Undefined,
    'Float + Undefined': BaseTypes.Undefined,
    'Undefined + String': BaseTypes.Undefined,
    'String + Undefined': BaseTypes.Undefined,
    'Undefined - Undefined': BaseTypes.Undefined,
    'Undefined - Null': BaseTypes.Undefined,
    'Null - Undefined': BaseTypes.Undefined,
    'Undefined - Any': BaseTypes.Undefined,
    'Any - Undefined': BaseTypes.Undefined,
    'Undefined - Boolean': BaseTypes.Undefined,
    'Boolean - Undefined': BaseTypes.Undefined,
    'Undefined - Integer': BaseTypes.Undefined,
    'Integer - Undefined': BaseTypes.Undefined,
    'Undefined - Float': BaseTypes.Undefined,
    'Float - Undefined': BaseTypes.Undefined,
    'Undefined - String': BaseTypes.Undefined,
    'String - Undefined': BaseTypes.Undefined,
    'Undefined ^ Undefined': BaseTypes.Undefined,
    'Undefined ^ Null': BaseTypes.Undefined,
    'Null ^ Undefined': BaseTypes.Undefined,
    'Undefined ^ Any': BaseTypes.Undefined,
    'Any ^ Undefined': BaseTypes.Undefined,
    'Undefined ^ Boolean': BaseTypes.Undefined,
    'Boolean ^ Undefined': BaseTypes.Undefined,
    'Undefined ^ Integer': BaseTypes.Undefined,
    'Integer ^ Undefined': BaseTypes.Undefined,
    'Undefined ^ Float': BaseTypes.Undefined,
    'Float ^ Undefined': BaseTypes.Undefined,
    'Undefined ^ String': BaseTypes.Undefined,
    'String ^ Undefined': BaseTypes.Undefined,
    'Undefined * Undefined': BaseTypes.Undefined,
    'Undefined * Null': BaseTypes.Undefined,
    'Null * Undefined': BaseTypes.Undefined,
    'Undefined * Any': BaseTypes.Undefined,
    'Any * Undefined': BaseTypes.Undefined,
    'Undefined * Boolean': BaseTypes.Undefined,
    'Boolean * Undefined': BaseTypes.Undefined,
    'Undefined * Integer': BaseTypes.Undefined,
    'Integer * Undefined': BaseTypes.Undefined,
    'Undefined * Float': BaseTypes.Undefined,
    'Float * Undefined': BaseTypes.Undefined,
    'Undefined * String': BaseTypes.Undefined,
    'String * Undefined': BaseTypes.Undefined,
    'Undefined / Undefined': BaseTypes.Undefined,
    'Undefined / Null': BaseTypes.Undefined,
    'Null / Undefined': BaseTypes.Undefined,
    'Undefined / Any': BaseTypes.Undefined,
    'Any / Undefined': BaseTypes.Undefined,
    'Undefined / Boolean': BaseTypes.Undefined,
    'Boolean / Undefined': BaseTypes.Undefined,
    'Undefined / Integer': BaseTypes.Undefined,
    'Integer / Undefined': BaseTypes.Undefined,
    'Undefined / Float': BaseTypes.Undefined,
    'Float / Undefined': BaseTypes.Undefined,
    'Undefined / String': BaseTypes.Undefined,
    'String / Undefined': BaseTypes.Undefined,
    'Null + Null': BaseTypes.Undefined,
    'Null + Any': BaseTypes.Undefined,
    'Any + Null': BaseTypes.Undefined,
    'Null + Boolean': BaseTypes.Undefined,
    'Boolean + Null': BaseTypes.Undefined,
    'Null + Integer': BaseTypes.Undefined,
    'Integer + Null': BaseTypes.Undefined,
    'Null + Float': BaseTypes.Undefined,
    'Float + Null': BaseTypes.Undefined,
    'Null + String': BaseTypes.Undefined,
    'String + Null': BaseTypes.Undefined,
    'Null - Null': BaseTypes.Undefined,
    'Null - Any': BaseTypes.Undefined,
    'Any - Null': BaseTypes.Undefined,
    'Null - Boolean': BaseTypes.Undefined,
    'Boolean - Null': BaseTypes.Undefined,
    'Null - Integer': BaseTypes.Undefined,
    'Integer - Null': BaseTypes.Undefined,
    'Null - Float': BaseTypes.Undefined,
    'Float - Null': BaseTypes.Undefined,
    'Null - String': BaseTypes.Undefined,
    'String - Null': BaseTypes.Undefined,
    'Null ^ Null': BaseTypes.Undefined,
    'Null ^ Any': BaseTypes.Undefined,
    'Any ^ Null': BaseTypes.Undefined,
    'Null ^ Boolean': BaseTypes.Undefined,
    'Boolean ^ Null': BaseTypes.Undefined,
    'Null ^ Integer': BaseTypes.Undefined,
    'Integer ^ Null': BaseTypes.Undefined,
    'Null ^ Float': BaseTypes.Undefined,
    'Float ^ Null': BaseTypes.Undefined,
    'Null ^ String': BaseTypes.Undefined,
    'String ^ Null': BaseTypes.Undefined,
    'Null * Null': BaseTypes.Undefined,
    'Null * Any': BaseTypes.Undefined,
    'Any * Null': BaseTypes.Undefined,
    'Null * Boolean': BaseTypes.Undefined,
    'Boolean * Null': BaseTypes.Undefined,
    'Null * Integer': BaseTypes.Undefined,
    'Integer * Null': BaseTypes.Undefined,
    'Null * Float': BaseTypes.Undefined,
    'Float * Null': BaseTypes.Undefined,
    'Null * String': BaseTypes.Undefined,
    'String * Null': BaseTypes.Undefined,
    'Null / Null': BaseTypes.Undefined,
    'Null / Any': BaseTypes.Undefined,
    'Any / Null': BaseTypes.Undefined,
    'Null / Boolean': BaseTypes.Undefined,
    'Boolean / Null': BaseTypes.Undefined,
    'Null / Integer': BaseTypes.Undefined,
    'Integer / Null': BaseTypes.Undefined,
    'Null / Float': BaseTypes.Undefined,
    'Float / Null': BaseTypes.Undefined,
    'Null / String': BaseTypes.Undefined,
    'String / Null': BaseTypes.Undefined,
    'Any + Any': BaseTypes.Any,
    'Any + Boolean': BaseTypes.Any,
    'Boolean + Any': BaseTypes.Any,
    'Any + Integer': BaseTypes.Any,
    'Integer + Any': BaseTypes.Any,
    'Any + Float': BaseTypes.Any,
    'Float + Any': BaseTypes.Any,
    'Any + String': BaseTypes.Any,
    'String + Any': BaseTypes.Any,
    'Any - Any': BaseTypes.Any,
    'Any - Boolean': BaseTypes.Any,
    'Boolean - Any': BaseTypes.Any,
    'Any - Integer': BaseTypes.Any,
    'Integer - Any': BaseTypes.Any,
    'Any - Float': BaseTypes.Any,
    'Float - Any': BaseTypes.Any,
    'Any - String': BaseTypes.Any,
    'String - Any': BaseTypes.Any,
    'Any ^ Any': BaseTypes.Any,
    'Any ^ Boolean': BaseTypes.Any,
    'Boolean ^ Any': BaseTypes.Any,
    'Any ^ Integer': BaseTypes.Any,
    'Integer ^ Any': BaseTypes.Any,
    'Any ^ Float': BaseTypes.Any,
    'Float ^ Any': BaseTypes.Any,
    'Any ^ String': BaseTypes.Any,
    'String ^ Any': BaseTypes.Any,
    'Any * Any': BaseTypes.Any,
    'Any * Boolean': BaseTypes.Any,
    'Boolean * Any': BaseTypes.Any,
    'Any * Integer': BaseTypes.Any,
    'Integer * Any': BaseTypes.Any,
    'Any * Float': BaseTypes.Any,
    'Float * Any': BaseTypes.Any,
    'Any * String': BaseTypes.Any,
    'String * Any': BaseTypes.Any,
    'Any / Any': BaseTypes.Any,
    'Any / Boolean': BaseTypes.Any,
    'Boolean / Any': BaseTypes.Any,
    'Any / Integer': BaseTypes.Any,
    'Integer / Any': BaseTypes.Any,
    'Any / Float': BaseTypes.Any,
    'Float / Any': BaseTypes.Any,
    'Any / String': BaseTypes.Any,
    'String / Any': BaseTypes.Any,
    'Boolean + Boolean': BaseTypes.Integer,
    'Boolean + Integer': BaseTypes.Integer,
    'Integer + Boolean': BaseTypes.Integer,
    'Boolean - Boolean': BaseTypes.Integer,
    'Boolean - Integer': BaseTypes.Integer,
    'Integer - Boolean': BaseTypes.Integer,
    'Boolean ^ Boolean': BaseTypes.Integer,
    'Boolean ^ Integer': BaseTypes.Integer,
    'Integer ^ Boolean': BaseTypes.Integer,
    'Boolean * Boolean': BaseTypes.Integer,
    'Boolean * Integer': BaseTypes.Integer,
    'Integer * Boolean': BaseTypes.Integer,
    'Boolean / Boolean': BaseTypes.Integer,
    'Boolean / Integer': BaseTypes.Integer,
    'Integer / Boolean': BaseTypes.Integer,
    'Boolean + Float': BaseTypes.Float,
    'Float + Boolean': BaseTypes.Float,
    'Boolean - Float': BaseTypes.Float,
    'Float - Boolean': BaseTypes.Float,
    'Boolean ^ Float': BaseTypes.Float,
    'Float ^ Boolean': BaseTypes.Float,
    'Boolean * Float': BaseTypes.Float,
    'Float * Boolean': BaseTypes.Float,
    'Boolean / Float': BaseTypes.Float,
    'Float / Boolean': BaseTypes.Float,
    'Boolean + String': BaseTypes.Undefined,
    'String + Boolean': BaseTypes.Undefined,
    'Boolean - String': BaseTypes.Undefined,
    'String - Boolean': BaseTypes.Undefined,
    'Boolean ^ String': BaseTypes.Undefined,
    'String ^ Boolean': BaseTypes.Undefined,
    'Boolean * String': BaseTypes.Undefined,
    'String * Boolean': BaseTypes.Undefined,
    'Boolean / String': BaseTypes.Undefined,
    'String / Boolean': BaseTypes.Undefined,
    'Integer + Integer': BaseTypes.Integer,
    'Integer - Integer': BaseTypes.Integer,
    'Integer ^ Integer': BaseTypes.Integer,
    'Integer * Integer': BaseTypes.Integer,
    'Integer / Integer': BaseTypes.Integer,
    'Integer + Float': BaseTypes.Float,
    'Float + Integer': BaseTypes.Float,
    'Integer - Float': BaseTypes.Float,
    'Float - Integer': BaseTypes.Float,
    'Integer ^ Float': BaseTypes.Float,
    'Float ^ Integer': BaseTypes.Float,
    'Integer * Float': BaseTypes.Float,
    'Float * Integer': BaseTypes.Float,
    'Integer / Float': BaseTypes.Float,
    'Float / Integer': BaseTypes.Float,
    'Integer + String': BaseTypes.String,
    'String + Integer': BaseTypes.String,
    'Integer - String': BaseTypes.String,
    'String - Integer': BaseTypes.String,
    'Integer ^ String': BaseTypes.String,
    'String ^ Integer': BaseTypes.String,
    'Integer * String': BaseTypes.String,
    'String * Integer': BaseTypes.String,
    'Integer / String': BaseTypes.String,
    'String / Integer': BaseTypes.String,
    'String + String': BaseTypes.String,
    'String - String': BaseTypes.String,
    'String ^ String': BaseTypes.String,
    'String * String': BaseTypes.String,
    'String / String': BaseTypes.String,
};
